//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductConsignment
    {
        public System.Guid id { get; set; }
        public string code { get; set; }
        public string sdk { get; set; }
        public string name { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.Guid> unit { get; set; }
        public string otherunits { get; set; }
        public string quycachsanpham { get; set; }
        public string thanhphan { get; set; }
        public string congdung { get; set; }
        public string chidinh { get; set; }
        public string chongchidinh { get; set; }
        public string lieudung_cachdung { get; set; }
        public string thantrong { get; set; }
        public bool choconbu { get; set; }
        public bool khananglaixe { get; set; }
        public string tuongtacthuoc { get; set; }
        public string tacdungkhongmuon { get; set; }
        public string qualieu_cachxuly { get; set; }
        public string baoquan { get; set; }
        public string handung { get; set; }
        public string tieuchuan { get; set; }
        public string cososanxuat { get; set; }
        public string diachisanxuat { get; set; }
        public string imanges { get; set; }
        public string filegdk { get; set; }
        public string filegknsp { get; set; }
        public string filegcnGMP { get; set; }
        public string baiviet { get; set; }
        public string giaycnthocgiatruyen { get; set; }
        public string danhmuchotro { get; set; }
        public string thuonghieu { get; set; }
        public string xuatxu { get; set; }
        public string nguongoc { get; set; }
        public string thanhphanhoahoc { get; set; }
        public string doituongsudung { get; set; }
        public string luuysudung { get; set; }
        public string soCOCQ { get; set; }
        public string fileCOCQ { get; set; }
        public int cannang { get; set; }
        public int ktcao { get; set; }
        public int ktdai { get; set; }
        public int ktrong { get; set; }
        public bool kiguisanpham { get; set; }
        public bool isdeleted { get; set; }
        public int status { get; set; }
        public string dateadded { get; set; }
        public Nullable<int> productcatalogid { get; set; }
        public bool isview { get; set; }
        public string sickcatalogid { get; set; }
        public string sick { get; set; }
        public string note { get; set; }
        public Nullable<System.Guid> evaluationid { get; set; }
        public Nullable<System.Guid> companyid { get; set; }
        public string evaluationdate { get; set; }
        public Nullable<System.Guid> productid { get; set; }
        public string chietxuat { get; set; }
        public decimal khohang { get; set; }
        public Nullable<bool> lathuocgiatruyen { get; set; }
    }
}
